-- =====================================================
-- V1: esquema relacional completo de AlimentaCR
-- PostgreSQL 18.6
--
-- Tablas:
-- 1. organizacion
-- 2. usuario
-- 3. categoria
-- 4. donacion
-- 5. solicitud
-- 6. entrega
-- =====================================================


-- =====================================================
-- ENUMERACIONES
-- =====================================================

CREATE TYPE tipo_organizacion AS ENUM (
    'DONANTE',
    'BENEFICIARIA'
);

CREATE TYPE estado_organizacion AS ENUM (
    'PENDIENTE',
    'APROBADA',
    'RECHAZADA',
    'INACTIVA'
);

CREATE TYPE rol_usuario AS ENUM (
    'ADMINISTRADOR',
    'REPRESENTANTE_DONANTE',
    'REPRESENTANTE_BENEFICIARIA'
);

CREATE TYPE estado_usuario AS ENUM (
    'ACTIVO',
    'INACTIVO'
);

CREATE TYPE estado_categoria AS ENUM (
    'ACTIVA',
    'INACTIVA'
);

CREATE TYPE unidad_medida AS ENUM (
    'KILOGRAMO',
    'GRAMO',
    'LITRO',
    'MILILITRO',
    'UNIDAD',
    'PAQUETE',
    'CAJA'
);

CREATE TYPE estado_donacion AS ENUM (
    'DISPONIBLE',
    'ASIGNADA',
    'ENTREGADA',
    'CANCELADA',
    'VENCIDA'
);

CREATE TYPE estado_solicitud AS ENUM (
    'PENDIENTE',
    'ACEPTADA',
    'RECHAZADA',
    'CANCELADA'
);

CREATE TYPE estado_entrega AS ENUM (
    'PENDIENTE',
    'FINALIZADA',
    'CANCELADA'
);


-- =====================================================
-- 1. TABLA ORGANIZACION
-- =====================================================

CREATE TABLE organizacion (
    id_organizacion BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    nombre VARCHAR(150) NOT NULL,

    tipo tipo_organizacion NOT NULL,

    cedula_juridica VARCHAR(30) NOT NULL,

    descripcion VARCHAR(500),

    direccion VARCHAR(250) NOT NULL,

    telefono VARCHAR(20) NOT NULL,

    estado estado_organizacion
        NOT NULL
        DEFAULT 'PENDIENTE',

    fecha_registro TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_organizacion
        PRIMARY KEY (id_organizacion),

    CONSTRAINT uq_organizacion_cedula_juridica
        UNIQUE (cedula_juridica),

    CONSTRAINT chk_organizacion_nombre_no_vacio
        CHECK (BTRIM(nombre) <> ''),

    CONSTRAINT chk_organizacion_cedula_no_vacia
        CHECK (BTRIM(cedula_juridica) <> ''),

    CONSTRAINT chk_organizacion_direccion_no_vacia
        CHECK (BTRIM(direccion) <> ''),

    CONSTRAINT chk_organizacion_telefono_no_vacio
        CHECK (BTRIM(telefono) <> '')
);


-- =====================================================
-- 2. TABLA USUARIO
-- =====================================================

CREATE TABLE usuario (
    id_usuario BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    id_organizacion BIGINT NOT NULL,

    nombre VARCHAR(150) NOT NULL,

    correo VARCHAR(150) NOT NULL,

    contrasena VARCHAR(255) NOT NULL,

    telefono VARCHAR(20),

    rol rol_usuario NOT NULL,

    estado estado_usuario
        NOT NULL
        DEFAULT 'ACTIVO',

    fecha_registro TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_usuario
        PRIMARY KEY (id_usuario),

    CONSTRAINT uq_usuario_correo
        UNIQUE (correo),

    CONSTRAINT fk_usuario_organizacion
        FOREIGN KEY (id_organizacion)
        REFERENCES organizacion (id_organizacion)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_usuario_nombre_no_vacio
        CHECK (BTRIM(nombre) <> ''),

    CONSTRAINT chk_usuario_correo_no_vacio
        CHECK (BTRIM(correo) <> ''),

    CONSTRAINT chk_usuario_contrasena_no_vacia
        CHECK (BTRIM(contrasena) <> ''),

    CONSTRAINT chk_usuario_telefono_valido
        CHECK (
            telefono IS NULL
            OR BTRIM(telefono) <> ''
        )
);


-- =====================================================
-- 3. TABLA CATEGORIA
-- =====================================================

CREATE TABLE categoria (
    id_categoria BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    nombre VARCHAR(100) NOT NULL,

    descripcion VARCHAR(250),

    estado estado_categoria
        NOT NULL
        DEFAULT 'ACTIVA',

    CONSTRAINT pk_categoria
        PRIMARY KEY (id_categoria),

    CONSTRAINT uq_categoria_nombre
        UNIQUE (nombre),

    CONSTRAINT chk_categoria_nombre_no_vacio
        CHECK (BTRIM(nombre) <> '')
);


-- =====================================================
-- 4. TABLA DONACION
-- =====================================================

CREATE TABLE donacion (
    id_donacion BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    id_organizacion_donante BIGINT NOT NULL,

    id_categoria BIGINT NOT NULL,

    alimento VARCHAR(150) NOT NULL,

    descripcion VARCHAR(500),

    cantidad DECIMAL(10,2) NOT NULL,

    unidad_medida unidad_medida NOT NULL,

    fecha_publicacion TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    fecha_limite_retiro DATE NOT NULL,

    estado estado_donacion
        NOT NULL
        DEFAULT 'DISPONIBLE',

    CONSTRAINT pk_donacion
        PRIMARY KEY (id_donacion),

    CONSTRAINT fk_donacion_organizacion
        FOREIGN KEY (id_organizacion_donante)
        REFERENCES organizacion (id_organizacion)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_donacion_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categoria (id_categoria)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_donacion_alimento_no_vacio
        CHECK (BTRIM(alimento) <> ''),

    CONSTRAINT chk_donacion_cantidad_positiva
        CHECK (cantidad > 0),

    CONSTRAINT chk_donacion_fecha_limite
        CHECK (
            fecha_limite_retiro
            > fecha_publicacion::DATE
        )
);


-- =====================================================
-- 5. TABLA SOLICITUD
-- =====================================================

CREATE TABLE solicitud (
    id_solicitud BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    id_donacion BIGINT NOT NULL,

    id_organizacion_beneficiaria BIGINT NOT NULL,

    fecha_solicitud TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    estado estado_solicitud
        NOT NULL
        DEFAULT 'PENDIENTE',

    observacion VARCHAR(500),

    CONSTRAINT pk_solicitud
        PRIMARY KEY (id_solicitud),

    CONSTRAINT fk_solicitud_donacion
        FOREIGN KEY (id_donacion)
        REFERENCES donacion (id_donacion)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_solicitud_organizacion
        FOREIGN KEY (id_organizacion_beneficiaria)
        REFERENCES organizacion (id_organizacion)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_solicitud_observacion_valida
        CHECK (
            observacion IS NULL
            OR BTRIM(observacion) <> ''
        )
);


-- =====================================================
-- 6. TABLA ENTREGA
-- =====================================================

CREATE TABLE entrega (
    id_entrega BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    id_solicitud BIGINT NOT NULL,

    fecha_creacion TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    fecha_acordada TIMESTAMP,

    lugar VARCHAR(250),

    observaciones VARCHAR(500),

    confirmacion_donante BOOLEAN
        NOT NULL
        DEFAULT FALSE,

    confirmacion_beneficiario BOOLEAN
        NOT NULL
        DEFAULT FALSE,

    estado estado_entrega
        NOT NULL
        DEFAULT 'PENDIENTE',

    CONSTRAINT pk_entrega
        PRIMARY KEY (id_entrega),

    CONSTRAINT uq_entrega_solicitud
        UNIQUE (id_solicitud),

    CONSTRAINT fk_entrega_solicitud
        FOREIGN KEY (id_solicitud)
        REFERENCES solicitud (id_solicitud)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_entrega_fecha_acordada
        CHECK (
            fecha_acordada IS NULL
            OR fecha_acordada >= fecha_creacion
        ),

    CONSTRAINT chk_entrega_lugar_valido
        CHECK (
            lugar IS NULL
            OR BTRIM(lugar) <> ''
        ),

    CONSTRAINT chk_entrega_observaciones_validas
        CHECK (
            observaciones IS NULL
            OR BTRIM(observaciones) <> ''
        ),

    CONSTRAINT chk_entrega_finalizada_confirmada
        CHECK (
            estado <> 'FINALIZADA'
            OR (
                confirmacion_donante = TRUE
                AND confirmacion_beneficiario = TRUE
            )
        )
);


-- =====================================================
-- ÍNDICES PARA CLAVES FORÁNEAS Y CONSULTAS FRECUENTES
-- =====================================================

-- Consultar organizaciones según su estado de aprobación.
CREATE INDEX idx_organizacion_estado
    ON organizacion (estado);

-- Consultar los usuarios de una organización.
CREATE INDEX idx_usuario_organizacion
    ON usuario (id_organizacion);

-- Consultar usuarios activos o inactivos.
CREATE INDEX idx_usuario_estado
    ON usuario (estado);

-- Consultar las categorías activas.
CREATE INDEX idx_categoria_estado
    ON categoria (estado);

-- Consultar las donaciones de una organización.
CREATE INDEX idx_donacion_organizacion
    ON donacion (id_organizacion_donante);

-- Filtrar donaciones por categoría.
CREATE INDEX idx_donacion_categoria
    ON donacion (id_categoria);

-- Filtrar donaciones según estado y categoría.
CREATE INDEX idx_donacion_estado_categoria
    ON donacion (estado, id_categoria);

-- Consultar donaciones próximas a vencer.
CREATE INDEX idx_donacion_fecha_limite
    ON donacion (fecha_limite_retiro);

-- Consultar las solicitudes de una donación por estado.
CREATE INDEX idx_solicitud_donacion_estado
    ON solicitud (id_donacion, estado);

-- Consultar las solicitudes de una organización beneficiaria.
CREATE INDEX idx_solicitud_organizacion
    ON solicitud (id_organizacion_beneficiaria);

-- Consultar entregas pendientes o finalizadas.
CREATE INDEX idx_entrega_estado
    ON entrega (estado);

-- Consultar entregas según su fecha acordada.
CREATE INDEX idx_entrega_fecha_acordada
    ON entrega (fecha_acordada);


-- =====================================================
-- ÍNDICES ÚNICOS PARCIALES
-- =====================================================

-- Una donación puede recibir muchas solicitudes,
-- pero solo una puede estar aceptada.
CREATE UNIQUE INDEX uq_solicitud_aceptada_por_donacion
    ON solicitud (id_donacion)
    WHERE estado = 'ACEPTADA';


-- Una organización no puede tener dos solicitudes
-- pendientes para la misma donación.
CREATE UNIQUE INDEX uq_solicitud_pendiente_organizacion
    ON solicitud (
        id_donacion,
        id_organizacion_beneficiaria
    )
    WHERE estado = 'PENDIENTE';